baseurl = "https://tcolgate.github.io/"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-GB"
layoutdir = "layouts"
publishdir = "public"
author = "Tristan Colgate-McFarlane"
title = "Collected writings of a tinkerer"
pygmentsuseclasses = true
pluralizelisttitles = false
# theme = "local-cocoa"
theme = "rusty-typewriter"
cleanDestinationDir = true
copyright = ""
enableGitInfo = true
enableRobotsTXT = true

[pagination]
pageSize = 8

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
CacheBuster = true
DateForm = "Jan 2, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
Description = "Monitoring, SRE, and Miscellany"
#Email = "tcolgate@gmail.com"
FaviconFile = "img/leaf.ico"
GATracker = "XYZ"
GitHub = "//github.com/tcolgate"
HighlightJS = true
Initials = "tcm" # Displayed on single post page; DEPRECATED in v0.3.0.
Lang = "en"
LinkedIn = "//linkedin.com/in/tristan-colgate-762b052"
mastodon = "https://toot.community/@tmcfarlane"

[params.author]
name = "Tristan Colgate-McFarlane"

[params.rtwt]
  sidePane = true
  countPageItems = 7

[params.rtwt.home]
  showBio = false
  showAuthorImg = false
  sidePaneTags = true
  showFeatured = false
  showRecent = true
  hideRecentWhenFeatured = true
  countRecent = 5

[params.rtwt.side.home]
  sidePaneSticky = false
  taxonomies = ['categories','tags']
  countTaxonomy = 5

[params.rtwt.side.single]
  sidePaneSticky = true
  showDetails = true
  showTableOfContents = true
  showAttachments = true
  showRelated = true
  countRelated = 5
